### ISSUE TITLE
[feat] 개발용 데이터 추가

### ISSUE THREAD

**Issue by enjoy89** [styleKey/back#91]
### 🏋🏻 어떤 개발 사항인가요?

개발용 더미데이터 추가

### 💪🏻 TODO

- [x] 브랜드 데이터 추가
- [x] 코디룩, 아이템 데이터 추가
- [x] 스타일포인트 이미지 데이터 수정
